### ISSUE TITLE
Matching multiple types

### ISSUE THREAD

**Issue by mattlenz** [gaearon/react-dnd-html5-backend#2] opened 2015-10-20 23:50 UTC
Currently only the first matching data type is returned, however it is possible that dropped content may contain data of multiple types. For example when dropping a draggable image from another page, the `url` and `html` types may both be present.

Is there scope to rework the plugin to return all matched data types, rather than just the first match?

**Comment by gaearon** [comment] 2015-10-23 10:38
The problem is that React DnD (and [DnD Core](https://github.com/gaearon/dnd-core) underneath it) don't support the notion of "multiple types" for simplicity. Maybe you should use HTML5 API directly instead if you want this. Another option is to make an umbrella type for all HTML5 types, and instead make the specific “subtypes” available on the item object so you can read them in `canDrag`. That would be a breaking change for this backend, but we can do this if it covers all previous use cases and adds new ones.

**Comment by gaearon** [comment] 2015-11-03 00:11
Closing, as we don't have plans to implement this.
Feel free to come back with your experiments, if you make any!

**Closed as completed by gaearon** 2015-11-03 00:11 UTC

**Comment by mattlenz** [comment] 2015-11-03 00:12
Thanks Dan, I'll post if so.
