### ISSUE TITLE
File drop not working on the ReactDND website using Chrome

### ISSUE THREAD

**Issue by adityasan92** [gaearon/react-dnd-html5-backend#19] opened 2016-02-13 18:38 UTC
Hi, 

I am trying to get the file drop feature work. It seems to not be working on the http://gaearon.github.io/react-dnd/examples-dustbin-multiple-targets.html

I get the error:*\* Uncaught Invariant Violation: Cannot call hover while not dragging. **I am using Chrome. I am new to react and redux. Please help me thanks. 
![image](https://cloud.githubusercontent.com/assets/7659965/13029315/05e04fd2-d257-11e5-9fee-fca157275316.png)

**Comment by gaearon** [comment] 2016-02-13 21:33
I can’t reproduce this on OS X with Chrome 48. Please post your operating system (Windows, assuming from scroll bars), Chrome version, and exact sequence of steps to reproduce the problem.

**Comment by adityasan92** [comment] 2016-02-13 22:57
Hey gaearon, 

I am using windows 10, and the Chrome Version is 48.0.2564.109 m. I was trying to use the file drop feature on the website, so I tried dropping a txt file into the Dustbin that accepts the _Native_file_ on the website. that gave me the above error. When I use firefox it seems to be dropping but gives a warning as show below 
![image](https://cloud.githubusercontent.com/assets/7659965/13030497/39ab4032-d27b-11e5-9ab3-2e2248dea164.png)

Thanks for the reply. Big fan of ReactDND and Redux.

**Comment by gaearon** [comment] 2016-02-13 23:51
This should be fixed in `react-dnd-html5-backend@2.1.2`.
Please verify.

(I have not had time to update the website yet but I will later today.)

**Closed as completed by gaearon** 2016-02-13 23:51 UTC

**Comment by adityasan92** [comment] 2016-02-14 01:27
Thanks the new version works!!

**Comment by gaearon** [comment] 2016-02-14 01:28
I’m glad! (I had to buy a BrowserStack license to debug it :sweat_smile: )

**Comment by mrcrlee** [comment] 2016-05-10 00:08
Dan,

Thanks for your attention to this issue. 

I've discovered, while using in development and through the dustbin examples hosted on github, this issue does persist on the following platform:

Windows 7 Enterprise
Firefox: 38.5.0

Screenshot attached.

![dnderror](https://cloud.githubusercontent.com/assets/3240504/15131876/d2b97494-1621-11e6-818c-b3e67fe90fb8.png)

**Comment by stevengoldberg** [comment] 2016-08-09 20:35
Hey @gaearon, I've been seeing this pop up in my error logs as well -- looks like it's happening to users on Windows 7 and Windows 10, and all on Firefox 47, when they're trying to do something with file drag-and-drop. I've got `"react-dnd": "^2.1.4"` and `"react-dnd-html5-backend": "^2.1.2".`

**Comment by razjel** [comment] 2016-10-05 09:16
I also can't figure out how to solve this problem, but I discovered that It's most probably because of this fix in `HTML5Backend.js`

``` javascript
    // On Firefox, if mousemove fires, the drag is over but browser failed to tell us.
    // This is not true for other browsers.
    if (isFirefox()) {
      window.addEventListener('mousemove', this.endDragNativeItem, true);
    }
```
